# -*- coding: utf-8 -*-
"""Simulador_Planificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168Krq0ydL4n4cXeVK_RSzy58A7Rrbo8D
"""

import time
from collections import deque

class Proceso:
    def __init__(self, nombre, tiempo, prioridad, datos):
        self.nombre = nombre
        self.tiempo = tiempo
        self.prioridad = prioridad
        self.datos = datos
        self.estado = "Nuevo"

    def cambiar_estado(self, nuevo_estado):
        self.estado = nuevo_estado
        print(f"{self.nombre} -> {self.estado}")

# Algoritmo FIFO
def fifo(procesos):
    print("\n--- PLANIFICACION FIFO ---\n")

    for p in procesos:
        p.cambiar_estado("Listo")

    for p in procesos:
        p.cambiar_estado("En ejecución")

        for i in range(p.tiempo):
            print(f"{p.nombre} ejecutando... ({i+1}/{p.tiempo})")
            time.sleep(1)

        p.cambiar_estado("Bloqueado")
        time.sleep(1)
        p.cambiar_estado("Terminado")


# Algoritmo Round Robin
def round_robin(procesos, quantum=2):

    print("\n--- PLANIFICACION ROUND ROBIN ---\n")

    cola = deque()

    for p in procesos:
        p.cambiar_estado("Listo")
        cola.append(p)

    while cola:

        proceso = cola.popleft()

        proceso.cambiar_estado("En ejecución")

        tiempo_ejecucion = min(quantum, proceso.tiempo)

        for i in range(tiempo_ejecucion):
            print(f"{proceso.nombre} ejecutando...")
            time.sleep(1)

        proceso.tiempo -= tiempo_ejecucion

        if proceso.tiempo > 0:
            proceso.cambiar_estado("Listo")
            cola.append(proceso)
        else:
            proceso.cambiar_estado("Terminado")



# PROGRAMA PRINCIPAL

p1 = Proceso("Proceso1", 5, 1, 200)
p2 = Proceso("Proceso2", 3, 2, 100)
p3 = Proceso("Proceso3", 4, 3, 150)

procesos = [p1, p2, p3]

print("SIMULADOR PLANIFICADOR SIGET\n")

print("Procesos creados:")
for p in procesos:
    print(f"{p.nombre} | Tiempo:{p.tiempo} | Prioridad:{p.prioridad} | Datos:{p.datos}")

print("\nSeleccione algoritmo:")
print("1. FIFO")
print("2. Round Robin")

opcion = input("Opción: ")

if opcion == "1":
    fifo(procesos)

elif opcion == "2":
    round_robin(procesos)

else:
    print("Opción inválida")